### ISSUE TITLE
Register Asset without adding it to oracle token field leads to consensus failure

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#137]
## Version

develop(https://github.com/ExocoreNetwork/exocore/commit/2b00dd8bd3ea9298c984e3c0fc5b66d8286204c6)  + PR #132(https://github.com/ExocoreNetwork/exocore/pull/132/commits/de82413a93830b650a1eca8a699e00244119d4e9)  + PR #133(https://github.com/ExocoreNetwork/exocore/pull/133/commits/42837d9a7e4b202a62e3260aec43125401f7fd5b) + PR #136 https://github.com/ExocoreNetwork/exocore/pull/136/commits/f894ccf673548985aafcb9f4621b6d6749158348

## Steps to Reproduce

1. Register Client Chain via assets.
2. Register asset via assets module.
3. Validator failed with consensus failure.

```
exocored tx assets RegisterClientChain  "Holesky" "holesky" 40159 20 --from relayer --keyring-backend test --home /root/.testnetV3/node1 --fees 50000000000aexo --node http://localhost:20000

exocored tx assets RegisterAsset "Holesky Exo ETH" "hexoETH" 0x1E867667Ef16111047C2c7f6ADf4612bDf80064D "exoETH on holeksy" 100000000000000000000000000 40159 18 --home /root/.testnetV3/node1 --from relayer --keyring-backend test --fees 50000000000aexo --node http://localhost:20000
```
## Screenshots

error Log:

```
Jul 18 10:48:30 den-sm5038ml-h12trf-6-11 exocored[3648863]: 10:48AM INF AfterEpochEnd minted successfully=20000000000000000000aexo module=x/exomint
Jul 18 10:48:30 den-sm5038ml-h12trf-6-11 exocored[3648863]: 10:48AM INF prepare for next oracle round of each tokenFeeder height=913 module=x/oracle
Jul 18 10:48:30 den-sm5038ml-h12trf-6-11 exocored[3648863]: 10:48AM ERR CONSENSUS FAILURE!!! err="CalculateUSDValueForOperator, the input prices map is nil" module=consensus server=node stack="goroutine 137 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:736 +0x46\npanic({0x2e51700?, 0xc005e369c0?})\n\truntime/panic.go:914 +0x21f\ngithub.com/ExocoreNetwork/exocore/x/operator/keeper.(*Keeper).EndBlock(_, {{0x41ac720, 0x607c180}, {0x41c7e30, 0xc005da5b40}, {{0xb, 0x0}, {0xc002f10138, 0x14}, 0x391, ...}, ...}, ...)\n\tgithub.com/ExocoreNetwork/exocore/x/operator/keeper/abci.go:159 +0x10c\ngithub.com/ExocoreNetwork/exocore/x/operator.AppModule.EndBlock(...)\n\tgithub.com/ExocoreNetwork/exocore/x/operator/module.go:97\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x41ac720, 0x607c180}, {0x41c7e30, 0xc005da5b40}, {{0xb, 0x0}, {0xc002f10138, 0x14}, 0x391, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.47.8/types/module/module.go:583 +0x1c9\ngithub.com/ExocoreNetwork/exocore/app.(*ExocoreApp).EndBlocker(...)\n\tgithub.com/ExocoreNetwork/exocore/app/app.go:1144\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc0016685a0, {0x40?})\n\tgithub.com/cosmos/cosmos-sdk@v0.47.8/baseapp/abci.go:219 +0x165\ngithub.com/cometbft/cometbft/abci/client.(*localClient).EndBlockSync(0xc0033c7800, {0xc0008156c0?})\n\tgithub.com/cometbft/cometbft@v0.37.4/abci/client/local_client.go:291 +0xd3\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).EndBlockSync(0xc00351d7a0, {0xc0008156c0?})\n\tgithub.com/cometbft/cometbft@v0.37.4/proxy/app_conn.go:111 +0x14c\ngithub.com/cometbft/cometbft/state.execBlockOnProxyApp({0x41ac758?, 0xc00116dfe0}, {0x41c3e00, 0xc00351d7a0}, 0xc001d90b40, {0x41c8b68, 0xc003583398}, 0x390?)\n\tgithub.com/cometbft/cometbft@v0.37.4/state/execution.go:383 +0x6fc\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc002e10af0, 0x6}}, {0xc003514408, 0x14}, 0x1, 0x390, {{0xc002a61a00, ...}, ...}, ...}, ...)\n\tgithub.com/cometbft/cometbft@v0.37.4/state/execution.go:197 +0x165\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc00101ca80, 0x391)\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:1710 +0xa65\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc00101ca80, 0x391)\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:1619 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:1554 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc00101ca80, 0x391, 0x0)\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:1592 +0xc5b\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc00101ca80, 0xc0068e45a0, {0xc001212930, 0x28})\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:2223 +0x18ed\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc00101ca80, 0xc0068e45a0, {0xc001212930?, 0xc00716bc08?})\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:2012 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc00101ca80, {{0x417aa40, 0xc001737ce8}, {0xc001212930, 0x28}})\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:865 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc00101ca80, 0x0)\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:772 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 90\n\tgithub.com/cometbft/cometbft@v0.37.4/consensus/state.go:383 +0x10c\n"
```

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by leonz789** [comment]
assetID need to be bonded with corresponding token in oracle module.
and for the error message, update by #141  to make it clear

**Comment by leonz789** [comment]
https://github.com/ExocoreNetwork/exocore/pull/143 this PR introduced the check in assets module to prevent this panic
