### ISSUE TITLE
Undelegate ALL tokens from a Concensus Validator Stop Consensus Process

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#59]
## Summary of Bug

Undelegate all the amount from the consensus validator stop the concensus. 

## Version

https://github.com/ExocoreNetwork/exocore/commit/72dc82248cfeb3dd289ee4eb02f4fa9dbc4c753d (also tag 0.1.2)

## Steps to Reproduce

1. Prerequistion:  Intially operator1 operator2, operator3 has delegation amount `1000`, `1000`, `1000` from staker1, staker2, staker3.
2. Deposit/delegate/undelegate a partial amount of token from the operator1 with staker1 address.
3. Undelegate all the amount that staker1 has delegated to operator1, so operator1 will with 0 delegation.
4. Nodes stop consensus at the height `3980239`. 

## Screenshots

Node1 Logs: 

```
9:03AM ERR call delegation precompile error err="the divisor is zero" module="delegation precompile"
9:03AM ERR call delegation precompile error err="the divisor is zero" module="delegation precompile"
9:03AM ERR call delegation precompile error err="the divisor is zero" module="delegation precompile"
9:03AM INF Timed out dur=2988.580547 height=3980239 module=consensus round=0 server=node step=RoundStepNewHeight
9:03AM INF received proposal module=consensus proposal="Proposal{3980239/0 (64085B09F7C01AB98AACBE308484557EFAE28D1A02FDF52333C4F
9108BCD3966:1:5C5FE62BBB6C, -1) CF5C538143AA @ 2024-05-16T09:03:04.491327168Z}" server=node
9:03AM INF received complete proposal block hash=64085B09F7C01AB98AACBE308484557EFAE28D1A02FDF52333C4F9108BCD3966 height=3980239
module=consensus server=node
9:03AM INF finalizing commit of block hash=64085B09F7C01AB98AACBE308484557EFAE28D1A02FDF52333C4F9108BCD3966 height=3980239 module
=consensus num_txs=1 root=C8E71D545824E1C4D00D184D6C1C555FE22C0DEFE5D1C31C1234B6CAFFFC52B5 server=node
9:03AM INF minted coins from module account amount=6612332000000000aexo from=evm module=x/bank
9:03AM INF burned tokens from module account amount=6612332000000000aexo from=evm module=x/bank
9:03AM ERR CONSENSUS FAILURE!!! err="the divisor is zero" module=consensus server=node stack="goroutine 144 [running]:\nruntime/d
ebug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\tgithub
.com/cometbft/cometbft@v0.37.2/consensus/state.go:732 +0x46\npanic({0x2f28da0?, 0xc000f4de90?})\n\truntime/panic.go:914 +0x21f\ng
ithub.com/ExocoreNetwork/exocore/x/operator/keeper.(*Keeper).EndBlock(_, {{0x4123628, 0x5fd0380}, {0x413e6d0, 0xc01fe58900}, {{0x
b, 0x0}, {0xc01a8779c8, 0x14}, 0x3cbbcf, ...}, ...}, ...)\n\tgithub.com/ExocoreNetwork/exocore/x/operator/keeper/abci.go:123 +0x1
56\ngithub.com/ExocoreNetwork/exocore/x/operator.AppModule.EndBlock(...)\n\tgithub.com/ExocoreNetwork/exocore/x/operator/module.g
o:99\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x4123628, 0x5fd0380}, {0x413e6d0, 0xc01fe58900}, {{0xb,
 0x0}, {0xc01a8779c8, 0x14}, 0x3cbbcf, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.47.5/types/module/module.go:583 +0x1c9
\ngithub.com/ExocoreNetwork/exocore/app.(*ExocoreApp).EndBlocker(...)\n\tgithub.com/ExocoreNetwork/exocore/app/app.go:1153\ngithu
b.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000a30000, {0x40?})\n\tgithub.com/cosmos/cosmos-sdk@v0.47.5/baseapp/abci.g
o:219 +0x165\ngithub.com/cometbft/cometbft/abci/client.(*localClient).EndBlockSync(0xc002e803c0, {0xc02970a700?})\n\tgithub.com/c
ometbft/cometbft@v0.37.2/abci/client/local_client.go:291 +0xd3\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).EndBlockSy
nc(0xc002e82588, {0xc02970a700?})\n\tgithub.com/cometbft/cometbft@v0.37.2/proxy/app_conn.go:111 +0x14c\ngithub.com/cometbft/comet
bft/state.execBlockOnProxyApp({0x4123660?, 0xc0054c42b0}, {0x413a760, 0xc002e82588}, 0xc00d616f00, {0x413f038, 0xc002a292a8}, 0x3
cbbce?)\n\tgithub.com/cometbft/cometbft@v0.37.2/state/execution.go:383 +0x6fc\ngithub.com/cometbft/cometbft/state.(*BlockExecutor
).ApplyBlock(_, {{{0xb, 0x0}, {0xc004f7ecf4, 0x6}}, {0xc004ed5e60, 0x14}, 0x3c1b04, 0x3cbbce, {{0xc03389f960, ...}, ...}, ...}, .
..)\n\tgithub.com/cometbft/cometbft@v0.37.2/state/execution.go:197 +0x165\ngithub.com/cometbft/cometbft/consensus.(*State).finali
zeCommit(0xc0013e0000, 0x3cbbcf)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1700 +0xa65\ngithub.com/cometbft/come
tbft/consensus.(*State).tryFinalizeCommit(0xc0013e0000, 0x3cbbcf)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1609
 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/st
ate.go:1544 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc0013e0000, 0x3cbbcf, 0x0)\n\tgithub.com/cometbf
t/cometbft@v0.37.2/consensus/state.go:1582 +0xc5b\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc0013e0000, 0xc018ac
1b80, {0xc017e7ff80, 0x28})\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:2212 +0x18ed\ngithub.com/cometbft/cometbft
/consensus.(*State).tryAddVote(0xc0013e0000, 0xc018ac1b80, {0xc017e7ff80?, 0xc00189dc08?})\n\tgithub.com/cometbft/cometbft@v0.37.
2/consensus/state.go:2001 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc0013e0000, {{0x40f14e0, 0xc00e7f6d9
0}, {0xc017e7ff80, 0x28}})\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:861 +0x3ce\ngithub.com/cometbft/cometbft/co
nsensus.(*State).receiveRoutine(0xc0013e0000, 0x0)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:768 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 130\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:379 +0x10c\n"
```

Node2 Logs: 

```
9:03AM INF finalizing commit of block hash=64085B09F7C01AB98AACBE308484557EFAE28D1A02FDF52333C4F9108BCD3966 height=3980239 module=consensus num_txs=1 root=C8E71D545824E1C4D00D184D6C1C555FE22C0DEFE5D1C31C1234B6CAFFFC52B5 server=node
9:03AM INF minted coins from module account amount=6612332000000000aexo from=evm module=x/bank
9:03AM INF burned tokens from module account amount=6612332000000000aexo from=evm module=x/bank
9:03AM ERR CONSENSUS FAILURE!!! err="the divisor is zero" module=consensus server=node stack="goroutine 108 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:732 +0x46\npanic({0x2f28da0?, 0xc000b3d0e0?})\n\truntime/panic.go:914 +0x21f\ngithub.com/ExocoreNetwork/exocore/x/operator/keeper.(*Keeper).EndBlock(_, {{0x4123628, 0x5fd0380}, {0x413e6d0, 0xc006ac1600}, {{0xb, 0x0}, {0xc02ca593b0, 0x14}, 0x3cbbcf, ...}, ...}, ...)\n\tgithub.com/ExocoreNetwork/exocore/x/operator/keeper/abci.go:123 +0x156\ngithub.com/ExocoreNetwork/exocore/x/operator.AppModule.EndBlock(...)\n\tgithub.com/ExocoreNetwork/exocore/x/operator/module.go:99\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x4123628, 0x5fd0380}, {0x413e6d0, 0xc006ac1600}, {{0xb, 0x0}, {0xc02ca593b0, 0x14}, 0x3cbbcf, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.47.5/types/module/module.go:583 +0x1c9\ngithub.com/ExocoreNetwork/exocore/app.(*ExocoreApp).EndBlocker(...)\n\tgithub.com/ExocoreNetwork/exocore/app/app.go:1153\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc0000765a0, {0x40?})\n\tgithub.com/cosmos/cosmos-sdk@v0.47.5/baseapp/abci.go:219 +0x165\ngithub.com/cometbft/cometbft/abci/client.(*localClient).EndBlockSync(0xc000ffa540, {0xc00ba74380?})\n\tgithub.com/cometbft/cometbft@v0.37.2/abci/client/local_client.go:291 +0xd3\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).EndBlockSync(0xc000ff8bd0, {0xc00ba74380?})\n\tgithub.com/cometbft/cometbft@v0.37.2/proxy/app_conn.go:111 +0x14c\ngithub.com/cometbft/cometbft/state.execBlockOnProxyApp({0x4123660?, 0xc00143fb90}, {0x413a760, 0xc000ff8bd0}, 0xc0008970e0, {0x413f038, 0xc000ff80c0}, 0x3cbbce?)\n\tgithub.com/cometbft/cometbft@v0.37.2/state/execution.go:383 +0x6fc\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0048abd44, 0x6}}, {0xc004829c20, 0x14}, 0x3c1b04, 0x3cbbce, {{0xc0119b8b60, ...}, ...}, ...}, ...)\n\tgithub.com/cometbft/cometbft@v0.37.2/state/execution.go:197 +0x165\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc00042b500, 0x3cbbcf)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1700 +0xa65\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc00042b500, 0x3cbbcf)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1609 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1544 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc00042b500, 0x3cbbcf, 0x0)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1582 +0xc5b\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc00042b500, 0xc01002f860, {0xc004e2c060, 0x28})\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:2212 +0x18ed\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc00042b500, 0xc01002f860, {0xc004e2c060?, 0xc001bcdc08?})\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:2001 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc00042b500, {{0x40f14e0, 0xc00ab6f900}, {0xc004e2c060, 0x28}})\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:861 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc00042b500, 0x0)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:768 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 85\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:379 +0x10c\n"
```

Node3 Logs:

```
9:03AM INF received complete proposal block hash=64085B09F7C01AB98AACBE308484557EFAE28D1A02FDF52333C4F9108BCD3966 height=3980239 module=consensus server=node
9:03AM INF finalizing commit of block hash=64085B09F7C01AB98AACBE308484557EFAE28D1A02FDF52333C4F9108BCD3966 height=3980239 module=consensus num_txs=1 root=C8E71D545824E1C4D00D184D6C1C555FE22C0DEFE5D1C31C1234B6CAFFFC52B5 server=node
9:03AM INF minted coins from module account amount=6612332000000000aexo from=evm module=x/bank
9:03AM INF burned tokens from module account amount=6612332000000000aexo from=evm module=x/bank
9:03AM ERR CONSENSUS FAILURE!!! err="the divisor is zero" module=consensus server=node stack="goroutine 157 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:732 +0x46\npanic({0x2f28da0?, 0xc000f19110?})\n\truntime/panic.go:914 +0x21f\ngithub.com/ExocoreNetwork/exocore/x/operator/keeper.(*Keeper).EndBlock(_, {{0x4123628, 0x5fd0380}, {0x413e6d0, 0xc01c065300}, {{0xb, 0x0}, {0xc02a254a50, 0x14}, 0x3cbbcf, ...}, ...}, ...)\n\tgithub.com/ExocoreNetwork/exocore/x/operator/keeper/abci.go:123 +0x156\ngithub.com/ExocoreNetwork/exocore/x/operator.AppModule.EndBlock(...)\n\tgithub.com/ExocoreNetwork/exocore/x/operator/module.go:99\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x4123628, 0x5fd0380}, {0x413e6d0, 0xc01c065300}, {{0xb, 0x0}, {0xc02a254a50, 0x14}, 0x3cbbcf, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.47.5/types/module/module.go:583 +0x1c9\ngithub.com/ExocoreNetwork/exocore/app.(*ExocoreApp).EndBlocker(...)\n\tgithub.com/ExocoreNetwork/exocore/app/app.go:1153\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000130780, {0x40?})\n\tgithub.com/cosmos/cosmos-sdk@v0.47.5/baseapp/abci.go:219 +0x165\ngithub.com/cometbft/cometbft/abci/client.(*localClient).EndBlockSync(0xc000b04660, {0xc008ba1880?})\n\tgithub.com/cometbft/cometbft@v0.37.2/abci/client/local_client.go:291 +0xd3\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).EndBlockSync(0xc000aff368, {0xc008ba1880?})\n\tgithub.com/cometbft/cometbft@v0.37.2/proxy/app_conn.go:111 +0x14c\ngithub.com/cometbft/cometbft/state.execBlockOnProxyApp({0x4123660?, 0xc001b8b080}, {0x413a760, 0xc000aff368}, 0xc003d1a5a0, {0x413f038, 0xc000afe858}, 0x3cbbce?)\n\tgithub.com/cometbft/cometbft@v0.37.2/state/execution.go:383 +0x6fc\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc003e51864, 0x6}}, {0xc0038996f8, 0x14}, 0x3c1b04, 0x3cbbce, {{0xc01616d760, ...}, ...}, ...}, ...)\n\tgithub.com/cometbft/cometbft@v0.37.2/state/execution.go:197 +0x165\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc000e67500, 0x3cbbcf)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1700 +0xa65\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc000e67500, 0x3cbbcf)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1609 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1544 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc000e67500, 0x3cbbcf, 0x0)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:1582 +0xc5b\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc000e67500, 0xc019d8fcc0, {0xc004db8120, 0x28})\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:2212 +0x18ed\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc000e67500, 0xc019d8fcc0, {0xc004db8120?, 0xc00161dc08?})\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:2001 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc000e67500, {{0x40f14e0, 0xc0105d6510}, {0xc004db8120, 0x28}})\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:861 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc000e67500, 0x0)\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:768 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 101\n\tgithub.com/cometbft/cometbft@v0.37.2/consensus/state.go:379 +0x10c\n"
```

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cloud8little** [comment]
Solved by #60, closed.
