### ISSUE TITLE
Empty validator set when starting a new node without historical chain data.

### ISSUE THREAD

**Issue by TimmyExogenous** [ExocoreNetwork/exocore#88]
## Summary of Bug

The first block process will cause the empty validator set when starting a new node without the historical chain data. It might be an Intermittent issue.

## Version

[V1.0.0](https://github.com/ExocoreNetwork/exocore/releases/tag/v1.0.0)

## Steps to Reproduce
1. Start a single node with local_node.sh
2. Using `init-4-nodes_testnet.py` to init two nodes. The script has been changed to set the local node to the persistent peers.
3. Copy the `genesis.json` of the local node to the new nodes.
4. register the new operator and opt into the dogfood.
5. Start node1, the two-nodes network works well.
6. Start node 2 after the network has been running for a period. Then the issue occurred.

The issue can be fixed by copying the historical `data` of node 1 to node 2.

## Screenshots

```bash
8:05PM INF Error reconnecting to peer. Trying again addr=591631f4b1f019bd0702061f2ac245e1124a9d17@127.0.0.1:26656 err="auth failure: secret conn failed: EOF" module=p2p server=node tries=0
8:05PM INF service start impl="Peer{MConn{127.0.0.1:30000} 5b5b3e2f231a66386a5deb4033660a2be0cb2c8f out}" module=p2p msg="Starting Peer service" peer=5b5b3e2f231a66386a5deb4033660a2be0cb2c8f@127.0.0.1:30000 server=node
8:05PM INF service start impl=MConn{127.0.0.1:30000} module=p2p msg="Starting MConnection service" peer=5b5b3e2f231a66386a5deb4033660a2be0cb2c8f@127.0.0.1:30000 server=node
8:05PM INF starting epoch identifier=day module=x/epochs
8:05PM INF starting epoch identifier=hour module=x/epochs
8:05PM INF starting epoch identifier=week module=x/epochs
8:05PM INF the prev validator is: addr=exovalcons18z3p42xn8pjk338upvzp794h02wh7p4t7jj9jx module=x/dogfood power=5000
8:05PM INF call dogfood abi endBlock 1111 len(ValidatorUpdate)=0 module=x/dogfood
8:05PM INF call dogfood abi endBlock 2222 len(ValidatorUpdate)=1 module=x/dogfood
8:05PM INF validator set changed, force seal all active rounds module=x/oracle
8:05PM INF prepare for next oracle round of each tokenFeeder module=x/oracle
8:05PM INF executed block height=1 module=state num_invalid_txs=0 num_valid_txs=0 server=node
8:05PM INF updates to validators module=state server=node updates=38A21AA8D3386568C4FC0B041F16B77A9D7F06AB:0
panic: Failed to process committed block (1:40FC3E734982E1203B80B1CCAC7DBC25783C8EDD94189499D922B6AED6DCBC21): commit failed for application: error changing validator set: applying the validator changes would result in empty set

goroutine 154 [running]:
github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc000fc2c40, 0x0)
	github.com/cometbft/cometbft@v0.37.4/blocksync/reactor.go:408 +0x126e
created by github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart in goroutine 1
	github.com/cometbft/cometbft@v0.37.4/blocksync/reactor.go:125 +0x6e
```

**Comment by MaxMustermann2** [comment]
Fixed by #98
